version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      opentelemetry:
        patterns:
          - "*opentelemetry*"  # Include all dependencies in one PR

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: weekly
