version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      opentelemetry:
        patterns: ["*opentelemetry*"]
      all:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: weekly
